#ref : https://velog.io/@neulhan/Github-actions-%EC%99%80-AWS-Code-Deploy%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-Django-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94
version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - directory
      - file
files:
  - source: ./
    destination: /home/ubuntu/TrAiAngle_2
hooks:
 BeforeInstall:
   - location: scripts/beforeInstall.sh
 AfterInstall:
   - location: scripts/afterInstall.sh